assigness: []
harvest_options:
  goldcopy: true
  path: s3://ooi-data
  refresh: true
  test: false
instrument: CE06ISSP-SP001-10-PARADJ000
stream:
  method: telemetered
  name: parad_j_cspp_instrument
workflow_config:
  schedule: 0 0 * * *
